### ISSUE TITLE
Refactor Storybook to use components

### ISSUE THREAD

**Issue by ianb** [FirefoxUX/photon-components-web#15]
Right now everything is in storybook.js, and doesn't use the button components or other components.

**Comment by lmorchard** [comment]
Sounds like a big deal, but isn't really. Basically, we just need to start writing using the Button component in these stories, rather than `<button>`

https://github.com/FirefoxUX/photon-components-web/blob/master/components/Button/stories.js#L8

**Comment by lmorchard** [comment]
I think I might just call this a dupe of #19 - as part of making Button a component, starting to use that component in the associated story will fix this issue, so...
