### ISSUE TITLE
[Component] Tabs

### ISSUE THREAD

**Issue by weivicky** [FirefoxUX/photon-components-web#2]
Hello!

I was working on tabs with @aminalhazwani . We created a prototype of tabs in Codepen and wondering if someone can implement it, so we can add them to Photon Design System.

https://codepen.io/weivicky/pen/aaVKPd 

<img width="667" alt="image" src="https://user-images.githubusercontent.com/10877399/46100867-82e47480-c198-11e8-8619-00b6229d1848.png">

<img width="661" alt="image" src="https://user-images.githubusercontent.com/10877399/46100880-8972ec00-c198-11e8-8217-2ae1fc64c088.png">

Thanks!!

**Comment by aminalhazwani** [comment]
YAY @weivicky! Can I only ask you to convert the picture in text? Many thanks!

**Comment by ianb** [comment]
@bwinton is going to ask @aminalhazwani about the status of the design spec on these

**Comment by aminalhazwani** [comment]
I tried to visualize the work of @weivicky in these two assets (cc @shorlander):

**Colors**

![colors](https://user-images.githubusercontent.com/1721875/46953956-909e6300-d08f-11e8-8075-c12c3521a51d.jpg)

**Sizes**

![sizes](https://user-images.githubusercontent.com/1721875/46953988-a1e76f80-d08f-11e8-9384-2790f8a22afa.jpg)

While we wait for Stephen's feedback, @ianb let me know if anything is missing from the specs. Something that comes to my mind is motion/animation but we can work out those details once we start implementing this new component.

**Comment by weivicky** [comment]
Hello, Amin! Sorry, I am not very active on Github, so didn't see the messages till now. But here are the specs for dark theme! Thanks for following up for me!!
![image](https://user-images.githubusercontent.com/10877399/46969901-8bd4b180-d085-11e8-82b9-87112351e04e.png)

My last comments:
1. the tab lines in the hover and pressed state are very light and nearly impossible to see. Should we make the tab lines more obvious? or should we leave it for consistency purposes?
2. still not sure why the active tab text label uses Grey 10
In the default theme for Firefox browser, the active tab uses a primary text color while the inactive tabs use a secondary color
![image](https://user-images.githubusercontent.com/10877399/46970292-b2471c80-d086-11e8-957e-045a60e9bdb8.png)
3. should we make the active tab clickable/hoverable/pressible? I originally had the hover/pressed states for the tabs as well but I thought about it deeper and wanted to remove them because nothing happens when you click on the tab. Point of hover is to show that something is clickable?

**Comment by aminalhazwani** [comment]
Hello there, following @weivicky feedback/question here the spec for dark theme:

![colors dark](https://user-images.githubusercontent.com/1721875/47156799-29c7b680-d2e8-11e8-9ae0-56e18e597b71.jpg)

For @weivicky

> the tab lines in the hover and pressed state are very light and nearly impossible to see. Should we make the tab lines more obvious? or should we leave it for consistency purposes?

Yeah, we increased the contrast. Hover is Grey 10 a10 and tab line is Grey 10 a20.

> still not sure why the active tab text label uses Grey 10

Yeah, it makes sense to use Blue 40

> should we make the active tab clickable/hoverable/pressible? I originally had the hover/pressed states for the tabs as well but I thought about it deeper and wanted to remove them because nothing happens when you click on the tab. Point of hover is to show that something is clickable?

Yeah, keeping the hover/press state hints user that the element is enabled and not disabled, even if it's the active/current one.
