### ISSUE TITLE
[Component] Collapsable trees

### ISSUE THREAD

**Issue by ianb** [FirefoxUX/photon-components-web#28]
Per [the specification](https://firefox-dev.tools/photon/components/trees.html)

**Comment by nt1m** [comment]
@ianb The specification that's linked seems to be for DevTools, something like about:performance might be more general ?

**Comment by bwinton** [comment]
@nt1m It might be, but there is no spec for that. Perhaps you can make a PR against https://github.com/devtools-html/photon/ adding the extra optional style for that kind of tree?
