### ISSUE TITLE
[Component] Overlay

### ISSUE THREAD

**Issue by ianb** [FirefoxUX/photon-components-web#32]
See the [overlay pattern](https://firefox-dev.tools/photon/patterns/overlay.html) for a brief description of the shadowbox effect:

![image](https://user-images.githubusercontent.com/44390/47177452-0e57ae00-d2de-11e8-96c9-1d6aeb4c20a1.png)

**Comment by ericawright** [comment]
Anyone mind if I take this?

**Comment by lmorchard** [comment]
Sure! If it's not assigned, it's fair game.

**Comment by ericawright** [comment]
thank, just wanted to comment since I can't assign myself

**Comment by lmorchard** [comment]
1b95cb46828a88a4f686a131b00486df7b0fd7ad
