### ISSUE TITLE
Add README story for each component?

### ISSUE THREAD

**Issue by lmorchard** [FirefoxUX/photon-components-web#48]
In PR #45, [I added ReactMarkdown to render the overall project README.md as an introduction in the storybook build](https://github.com/FirefoxUX/photon-components-web/blob/master/stories.js#L8). 

We're starting to get README.md per-component - so it might be nice to add a README.md case for each component?

**Comment by meandavejustice** [comment]
Would be good to include a template for each component readme. 

I'm thinking:
* Title
* link to storybook
* link to repo section
* Style section
* import example
* example with markup and css classes
* example with React component
* States/Variants section

**Comment by lmorchard** [comment]
Yeah, a template would be good. I've just been kind of fudging through them on my PRs without a really good idea of what belongs in them. On one hand it seems weird to repeat what's in the Storybook. On the other hand, it helps to have a place for some further info about the component.
