### ISSUE TITLE
Stop using ::after hack for checkboxes/radios

### ISSUE THREAD

**Issue by nt1m** [FirefoxUX/photon-components-web#59]
The markup for checkboxes should just be `<input type="checkbox" class="checkbox">`, nothing else... It doesn't make sense IMO to force putting a label as a wrapper and as a sibling element.

Plus, Firefox and Chrome (and possibly other major browsers, but I haven't checked), support styling `<input type="checkbox">` directly using -moz-appearance: none;

**Comment by lmorchard** [comment]
My CSS isn't very strong - which is probably why I used the ::after hack. Can you point to any working examples of how to improve the styling here?

**Comment by nt1m** [comment]
https://searchfox.org/mozilla-central/source/toolkit/themes/shared/in-content/common.inc.css#472-490,497-506

**Comment by lmorchard** [comment]
TIL about `-{webkit,moz}-appearance: none` - seems to work on Chrome, Edge, and Firefox!
