### ISSUE TITLE
Gestures for Mac on Firefox Browser

### ISSUE THREAD

**Issue by weivicky** [FirefoxUX/photon-components-web#79]
Hello! 

I notice that on Firefox browser, I can't use mac gestures (ex. zoom in and out with my fingers). Not sure if this is a topic that's been discussed before, but I think it would be cool!

**Comment by lmorchard** [comment]
I'm not sure that's something we can affect on this project. Maybe more of an overall Firefox issue?

**Comment by weivicky** [comment]
LOL True! I am not sure where to post the suggestion so I posted it here. Just ignore it then :) Thanks for the quick reply!

**Comment by lmorchard** [comment]
You might try Bugzilla, I think there are some existing bugs around this:

https://bugzilla.mozilla.org/buglist.cgi?quicksearch=mac+gestures
