### ISSUE TITLE
Token consideration list

### ISSUE THREAD

**Issue by johngruen** [FirefoxUX/photon-components-web#86]
Lets keep a list of everything we might want to tokenize

**Comment by brassy-** [comment]
Hey @johngruen! I put together a list of things. 

**Essential**
- [ ] Colors
- [ ] Font Size
- [ ] Spacing
- [ ] Shadow
- [ ] Opacity
- [ ]  Media Query

**Nice to have**
- [ ] Background Color
- [ ] Text Color
- [ ] Border Color
- [ ]  Font Family
- [ ] Line Height
- [ ] Radius
- [ ] Sizing
- [ ] Z-index
