### ISSUE TITLE
manager styles and preview styles do not seem to work

### ISSUE THREAD

**Issue by johngruen** [FirefoxUX/photon-components-web#89]

**Comment by lmorchard** [comment]
Looks like the custom HtmlWebpackPlugin config is breaking the inclusion of manager-head.html and preview-head.html. [Disabling this plugin replacement fixes it.](https://github.com/FirefoxUX/photon-components-web/blob/master/.storybook/webpack.config.js#L12) Should be a clue to fixing this issue while keeping the ability to customize the page template overall.
