### ISSUE TITLE
Switch to photon-icons check image for checkbox when available

### ISSUE THREAD

**Issue by lmorchard** [FirefoxUX/photon-components-web#91]
The checkbox component [is using a local image for the check icon](https://github.com/FirefoxUX/photon-components-web/blob/master/components/Checkbox/index.css#L27). We should [switch to a shared icon from photon icons](https://github.com/FirefoxUX/photon-components-web/pull/60#pullrequestreview-179967719) when available.

**Comment by nt1m** [comment]
@lmorchard According to https://github.com/FirefoxUX/icons/issues/79#issuecomment-403063753 , the checkbox on the icons website is the right one: https://design.firefox.com/icons/viewer/#check

**Comment by bwinton** [comment]
Really? Huh. Someone should update the Design System, then! 🙂
